# Generated by Django 3.2.5 on 2021-09-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210922_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_donate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=13, null=True),
        ),
    ]
